### ISSUE TITLE
pubsub not found

### ISSUE THREAD

**Issue by le-cardinal** [vfarcic/dapr-demo#1]
Hi,

when trying this demo (thanks for that), i'm not able to receive any publication done with curl command to add video, podcast or blog.

When lloking the logs of the publication pod, i always got following error
```
2023/11/06 19:14:20 http: panic serving 10.42.0.1:54432: error publishing event unto blog topic: rpc error: code = InvalidArgument desc = pubsub pubsub not found
goroutine 31 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1802 +0xb9
panic({0x8ea600, 0xc00000f200})
        /usr/local/go/src/runtime/panic.go:1047 +0x266
main.handlerAddBlog({0xa00ef8, 0xc0001a2380}, 0xc000192600)
        /src/main.go:93 +0x2e5
net/http.HandlerFunc.ServeHTTP(0x0, {0xa00ef8, 0xc0001a2380}, 0x0)
        /usr/local/go/src/net/http/server.go:2047 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc0001d628d, {0xa00ef8, 0xc0001a2380}, 0xc000192600)
        /usr/local/go/src/net/http/server.go:2425 +0x149
net/http.serverHandler.ServeHTTP({0xc000184f30}, {0xa00ef8, 0xc0001a2380}, 0xc000192600)
        /usr/local/go/src/net/http/server.go:2879 +0x43b
net/http.(*conn).serve(0xc000188320, {0xa024c0, 0xc00011efc0})
        /usr/local/go/src/net/http/server.go:1930 +0xb08
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3034 +0x4e8
2023/11/06 19:14:23 http: panic serving 10.42.0.1:65377: error publishing event unto blog topic: rpc error: code = InvalidArgument desc = pubsub pubsub not found
goroutine 33 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1802 +0xb9
panic({0x8ea600, 0xc00000f2a8})
        /usr/local/go/src/runtime/panic.go:1047 +0x266
main.handlerAddBlog({0xa00ef8, 0xc0001a2460}, 0xc000192700)
        /src/main.go:93 +0x2e5
net/http.HandlerFunc.ServeHTTP(0x4, {0xa00ef8, 0xc0001a2460}, 0x7f83c9d3f5b8)
        /usr/local/go/src/net/http/server.go:2047 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc0001d63cd, {0xa00ef8, 0xc0001a2460}, 0xc000192700)
        /usr/local/go/src/net/http/server.go:2425 +0x149
net/http.serverHandler.ServeHTTP({0xc000185290}, {0xa00ef8, 0xc0001a2460}, 0xc000192700)
        /usr/local/go/src/net/http/server.go:2879 +0x43b
net/http.(*conn).serve(0xc0001883c0, {0xa024c0, 0xc00011efc0})
        /usr/local/go/src/net/http/server.go:1930 +0xb08
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3034 +0x4e8
```
So i'm not able to make the pub/sub works against the dapr in my kubernetes cluster. Please note i'm working in local.

Regards

**Comment by le-cardinal** [comment]
be careful with the namespace name in redis.yaml file if you don't use production but another name
